"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Any

from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str) -> bool:
    """環境変数を真偽値として読む。未設定は False（本番の値は明示したときだけ効かせる）。"""
    return os.environ.get(name, "False").lower() in ("1", "true", "yes")


def env_list(name: str) -> list[str]:
    """カンマ区切りの環境変数をリストにする。未設定は空リスト。"""
    return [item.strip() for item in os.environ.get(name, "").split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 値は .env で設定する（.env.example をコピーして作成）
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "環境変数 DJANGO_SECRET_KEY が設定されていません。.env.example をコピーして .env を作成してください。"
    )

# SECURITY WARNING: don't run with debug turned on in production!
# 明示的に有効化しない限り False（安全側に倒す）
DEBUG = env_bool("DJANGO_DEBUG")

# カンマ区切りで指定する（例: DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]）
#
# [::1] は IPv6 のループバック。localhost は IPv4 と IPv6 の両方に解決され、
# ブラウザは IPv6 を優先することが多い。これを入れておかないと、
# 同じ localhost でもブラウザからだけ DisallowedHost で 400 になる。
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    # myapp を admin より前に置く。テンプレートは INSTALLED_APPS の順に検索されるため、
    # django.contrib.admin が持つ registration/password_*.html より
    # myapp 側のテンプレートを優先させる必要がある
    "myapp",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 本番の静的ファイル配信（DJANGO_PRODUCTION_STATIC=True のときだけ有効）。
# 開発・テストでは runserver と staticfiles が配信するので入れない（入れると
# staticfiles/ が無いという警告が出る。テストは collectstatic も通さない）。
PRODUCTION_STATIC = env_bool("DJANGO_PRODUCTION_STATIC")
if PRODUCTION_STATIC:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 本番はボリューム上に置くため、パスを環境変数で変えられるようにする。
DATABASES: dict[str, dict[str, Any]] = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": Path(os.environ.get("DJANGO_DB_PATH") or BASE_DIR / "db.sqlite3"),
    }
}

# 本番（DJANGO_SQLITE_WAL=True）の SQLite 設定。公開すると読み手と書き手が同時に来るため、
# WAL（読み取りが書き込みを待たない）、書き込みトランザクションを最初から取る IMMEDIATE
# （途中で昇格して "database is locked" になるのを避ける）、ロックの待ちを20秒にする。
# 開発・テストの動作は変えない。
if env_bool("DJANGO_SQLITE_WAL"):
    DATABASES["default"]["OPTIONS"] = {
        "transaction_mode": "IMMEDIATE",
        "timeout": 20,
        "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# collectstatic の出力先（gitignore 済み）。本番イメージはビルド時にここへ集める
STATIC_ROOT = BASE_DIR / "staticfiles"

if PRODUCTION_STATIC:
    # ファイル名にハッシュを付けて長期キャッシュできるようにし、gzip / brotli でも配信する。
    # manifest に無いファイルは例外になるので、collectstatic を通さないテストでは使わない
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# HTTPS の終端（Cloudflare）の裏で動かすときの設定。いずれも環境変数を明示したときだけ効く。
# Cloudflare は X-Forwarded-Proto を付けて渡す（Tunnel 経由でも届く）ので、これで HTTPS のリクエストだと判定できる
if env_bool("DJANGO_BEHIND_PROXY"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")  # 例: https://example.com
SECURE_SSL_REDIRECT = env_bool("DJANGO_SSL_REDIRECT")
SESSION_COOKIE_SECURE = env_bool("DJANGO_SECURE_COOKIES")
CSRF_COOKIE_SECURE = env_bool("DJANGO_SECURE_COOKIES")
# HSTS（秒）。0 は出さない。出すときはサブドメインとプリロードも付ける
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS") or 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0

# ログを標準出力へ出す（DJANGO_LOG_TO_STDOUT=True のとき。docker compose logs で読める）。
# 開発・テストでは 404 などの警告でテスト出力が汚れるので入れない。
# 404 などはアクセスログ（gunicorn）に残るので、django.request は500系だけ出す
if env_bool("DJANGO_LOG_TO_STDOUT"):
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "plain": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
        },
        "handlers": {
            "console": {"class": "logging.StreamHandler", "formatter": "plain"},
        },
        "root": {"handlers": ["console"], "level": "WARNING"},
        "loggers": {
            "django.request": {"level": "ERROR"},
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"

MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",  # これで error が danger（赤色）になります
}
