# Generated by Django 5.2.10 on 2026-01-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_memo_author_alter_memo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
