# Generated by Django 5.2.10 on 2026-01-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_memo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
