# Generated by Django 5.2.10 on 2026-01-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_league_team_player_delete_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bats', models.IntegerField(default=0, verbose_name='打数')),
                ('hits', models.IntegerField(default=0, verbose_name='安打')),
                ('home_runs', models.IntegerField(default=0, verbose_name='本塁打')),
                ('runs_batted_in', models.IntegerField(default=0, verbose_name='打点')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='myapp.player')),
            ],
        ),
    ]
