# Generated by Django 5.2.10 on 2026-01-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_playerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('投手', '投手'), ('捕手', '捕手'), ('内野手', '内野手'), ('外野手', '外野手'), ('指名打者', '指名打者')], default='内野手', max_length=10),
        ),
    ]
