# Generated by Django 5.2.10 on 2026-01-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitcherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('innings_pitched', models.FloatField(default=0.0)),
                ('earned_runs', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitcher_stats', to='myapp.player')),
            ],
        ),
    ]
