# Generated by Django 5.2.10 on 2026-01-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pitcherstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcherstats',
            name='hits_allowed',
            field=models.IntegerField(default=0, verbose_name='被安打'),
        ),
        migrations.AddField(
            model_name='pitcherstats',
            name='walks_allowed',
            field=models.IntegerField(default=0, verbose_name='与四球'),
        ),
    ]
