# Generated by Django 5.2.10 on 2026-01-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pitcherstats_hits_allowed_pitcherstats_walks_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='doubles',
            field=models.IntegerField(default=0, verbose_name='二塁打'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='hit_by_pitch',
            field=models.IntegerField(default=0, verbose_name='死球'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='sacrifice_flies',
            field=models.IntegerField(default=0, verbose_name='犠飛'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='triples',
            field=models.IntegerField(default=0, verbose_name='三塁打'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='walks',
            field=models.IntegerField(default=0, verbose_name='四球'),
        ),
    ]
