# Generated by Django 5.2.10 on 2026-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_playerstats_doubles_playerstats_hit_by_pitch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='hits',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='singles',
            field=models.IntegerField(default=0, verbose_name='単打'),
        ),
    ]
