# Generated by Django 5.2.10 on 2026-08-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_playerstats_hits_playerstats_singles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'リーグ', 'verbose_name_plural': 'リーグ'},
        ),
        migrations.AlterModelOptions(
            name='pitcherstats',
            options={'verbose_name': '投球成績', 'verbose_name_plural': '投球成績'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': '選手', 'verbose_name_plural': '選手'},
        ),
        migrations.AlterModelOptions(
            name='playerstats',
            options={'verbose_name': '打撃成績', 'verbose_name_plural': '打撃成績'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'チーム', 'verbose_name_plural': 'チーム'},
        ),
        migrations.AlterField(
            model_name='league',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='リーグ名'),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='earned_runs',
            field=models.IntegerField(default=0, verbose_name='自責点'),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='innings_pitched',
            field=models.FloatField(default=0.0, verbose_name='投球回'),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='敗戦'),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='saves',
            field=models.IntegerField(default=0, verbose_name='セーブ'),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='strikeouts',
            field=models.IntegerField(default=0, verbose_name='奪三振'),
        ),
        migrations.AlterField(
            model_name='pitcherstats',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='勝利'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='在籍中'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='選手名'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(verbose_name='背番号'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('投手', '投手'), ('捕手', '捕手'), ('内野手', '内野手'), ('外野手', '外野手'), ('指名打者', '指名打者')], default='内野手', max_length=10, verbose_name='守備位置'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='myapp.team', verbose_name='チーム'),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='本拠地'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='myapp.league', verbose_name='リーグ'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='チーム名'),
        ),
    ]
