# Generated by Django 5.2.10 on 2026-08-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_league_options_alter_pitcherstats_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='シーズン')),
                ('wins', models.IntegerField(default=0, verbose_name='勝')),
                ('losses', models.IntegerField(default=0, verbose_name='敗')),
                ('ties', models.IntegerField(default=0, verbose_name='分')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_records', to='myapp.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': 'シーズン成績',
                'verbose_name_plural': 'シーズン成績',
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('team', 'year'), name='unique_team_season')],
            },
        ),
    ]
