# Generated by Django 5.2.10 on 2026-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_teamseasonrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'チーム', 'verbose_name_plural': 'チーム'},
        ),
        migrations.AddField(
            model_name='team',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
