# Generated by Django 5.2.10 on 2026-08-09 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_team_options_team_display_order'),
    ]

    operations = [
        # 制約はフィールドより先に外す。SQLite はフィールド削除でテーブルを
        # 作り直すため、削除する列を参照した制約が残っていると失敗する。
        migrations.RemoveConstraint(
            model_name='teamseasonrecord',
            name='unique_team_season',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teamseasonrecord',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'number'], 'verbose_name': '選手', 'verbose_name_plural': '選手'},
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='シーズン')),
                ('played_on', models.DateField(verbose_name='試合日')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='ホーム得点')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='ビジター得点')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='myapp.team', verbose_name='ビジター')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='myapp.team', verbose_name='ホーム')),
            ],
            options={
                'verbose_name': '試合',
                'verbose_name_plural': '試合',
                'ordering': ['-played_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GameBattingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bats', models.IntegerField(default=0, verbose_name='打数')),
                ('singles', models.IntegerField(default=0, verbose_name='単打')),
                ('doubles', models.IntegerField(default=0, verbose_name='二塁打')),
                ('triples', models.IntegerField(default=0, verbose_name='三塁打')),
                ('home_runs', models.IntegerField(default=0, verbose_name='本塁打')),
                ('runs_batted_in', models.IntegerField(default=0, verbose_name='打点')),
                ('walks', models.IntegerField(default=0, verbose_name='四球')),
                ('hit_by_pitch', models.IntegerField(default=0, verbose_name='死球')),
                ('sacrifice_flies', models.IntegerField(default=0, verbose_name='犠飛')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_lines', to='myapp.game', verbose_name='試合')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_batting', to='myapp.player', verbose_name='選手')),
            ],
            options={
                'verbose_name': '打撃成績',
                'verbose_name_plural': '打撃成績',
            },
        ),
        migrations.CreateModel(
            name='GamePitchingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_pitched', models.FloatField(default=0.0, verbose_name='投球回')),
                ('wins', models.IntegerField(default=0, verbose_name='勝利')),
                ('losses', models.IntegerField(default=0, verbose_name='敗戦')),
                ('saves', models.IntegerField(default=0, verbose_name='セーブ')),
                ('earned_runs', models.IntegerField(default=0, verbose_name='自責点')),
                ('strikeouts', models.IntegerField(default=0, verbose_name='奪三振')),
                ('hits_allowed', models.IntegerField(default=0, verbose_name='被安打')),
                ('walks_allowed', models.IntegerField(default=0, verbose_name='与四球')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_lines', to='myapp.game', verbose_name='試合')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pitching', to='myapp.player', verbose_name='選手')),
            ],
            options={
                'verbose_name': '投球成績',
                'verbose_name_plural': '投球成績',
            },
        ),
        migrations.DeleteModel(
            name='PitcherStats',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.DeleteModel(
            name='TeamSeasonRecord',
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='game_teams_differ'),
        ),
        migrations.AddConstraint(
            model_name='gamebattingline',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_game_batting'),
        ),
        migrations.AddConstraint(
            model_name='gamepitchingline',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_game_pitching'),
        ),
    ]
