# Generated by Django 5.2.10 on 2026-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_player_stint'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='corporate_team',
            field=models.CharField(blank=True, max_length=100, verbose_name='出身社会人チーム'),
        ),
        migrations.AddField(
            model_name='player',
            name='high_school',
            field=models.CharField(blank=True, max_length=100, verbose_name='出身高校'),
        ),
        migrations.AddField(
            model_name='player',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='出身大学'),
        ),
    ]
