# Generated by Django 5.2.10 on 2026-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_player_amateur_career'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'リーグ', 'verbose_name_plural': 'リーグ'},
        ),
        migrations.AddField(
            model_name='league',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
