# Generated by Django 5.2.10 on 2026-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_league_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='roof',
            field=models.CharField(blank=True, choices=[('屋外', '屋外'), ('ドーム', 'ドーム'), ('開閉式屋根', '開閉式屋根')], help_text='開閉式は、屋根を閉じれば天候に左右されません。', max_length=10, verbose_name='屋根'),
        ),
    ]
