# Generated by Django 5.2.10 on 2026-08-10 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_stadium_roof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captaincy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField(verbose_name='就任年')),
                ('to_year', models.IntegerField(blank=True, help_text='空欄なら現在も主将です。', null=True, verbose_name='退任年')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captaincies', to='myapp.player', verbose_name='選手')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captaincies', to='myapp.team', verbose_name='チーム')),
            ],
            options={
                'verbose_name': '主将在任',
                'verbose_name_plural': '主将在任',
                'ordering': ['-from_year'],
                'constraints': [models.UniqueConstraint(fields=('player', 'team', 'from_year'), name='unique_captaincy_player_team_from')],
            },
        ),
    ]
