# Generated by Django 5.2.10 on 2026-08-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_captaincy'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_foreign_player',
            field=models.BooleanField(default=False, help_text='外国人枠の対象として数える選手かどうか。', verbose_name='外国人選手'),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='国籍'),
        ),
    ]
