# Generated by Django 5.2.10 on 2026-08-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_player_nationality_is_foreign_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='foreign_player_game_limit',
            field=models.PositiveIntegerField(blank=True, help_text='1試合に出場できる外国人選手の上限人数。空欄なら無制限。', null=True, verbose_name='外国人選手出場枠'),
        ),
        migrations.AddField(
            model_name='league',
            name='foreign_player_roster_limit',
            field=models.PositiveIntegerField(blank=True, help_text='登録できる外国人選手の上限人数。空欄なら無制限。', null=True, verbose_name='外国人選手登録枠'),
        ),
    ]
