# Generated by Django 5.2.10 on 2026-08-10 04:58
"""seed_virtual_players が出身地(birthplace)で表現していた助っ人選手を、
新設した is_foreign_player / nationality に移す。

都道府県リストはこの時点の判定基準を固定するため、management コマンド側の
リストを参照せずここに複製する（データマイグレーションを自己完結させる）。
"""

from django.db import migrations

JAPANESE_PREFECTURES = [
    '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
    '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
    '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県',
    '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府', '兵庫県',
    '奈良県', '和歌山県', '鳥取県', '島根県', '岡山県', '広島県', '山口県',
    '徳島県', '香川県', '愛媛県', '高知県', '福岡県', '佐賀県', '長崎県',
    '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県',
]


def backfill(apps, schema_editor):
    Player = apps.get_model('myapp', 'Player')
    foreign = Player.objects.exclude(birthplace='').exclude(
        birthplace__in=JAPANESE_PREFECTURES
    )
    for player in foreign:
        player.is_foreign_player = True
        player.nationality = player.birthplace
        player.save(update_fields=['is_foreign_player', 'nationality'])


def unset(apps, schema_editor):
    Player = apps.get_model('myapp', 'Player')
    Player.objects.exclude(birthplace='').exclude(
        birthplace__in=JAPANESE_PREFECTURES
    ).update(is_foreign_player=False, nationality='')


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_league_foreign_player_quota'),
    ]

    operations = [
        migrations.RunPython(backfill, unset),
    ]
