# Generated by Django 5.2.10 on 2026-08-10 05:26
"""既存のリーグで未設定（NULL＝無制限）だった外国人枠に、新しい既定値を入れる。

新規リーグはモデルの default で 5 / 3 になるが、この変更より前に作られた
リーグは既定値の変更が反映されないため、ここで明示的に埋める。
"""

from django.db import migrations


def backfill(apps, schema_editor):
    League = apps.get_model('myapp', 'League')
    League.objects.filter(foreign_player_roster_limit__isnull=True).update(
        foreign_player_roster_limit=5
    )
    League.objects.filter(foreign_player_game_limit__isnull=True).update(
        foreign_player_game_limit=3
    )


def unset(apps, schema_editor):
    League = apps.get_model('myapp', 'League')
    League.objects.filter(foreign_player_roster_limit=5).update(
        foreign_player_roster_limit=None
    )
    League.objects.filter(foreign_player_game_limit=3).update(
        foreign_player_game_limit=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_league_foreign_player_quota_defaults'),
    ]

    operations = [
        migrations.RunPython(backfill, unset),
    ]
