# Generated by Django 5.2.10 on 2026-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_backfill_league_foreign_player_quota_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='back_name',
            field=models.CharField(blank=True, help_text='ユニフォーム背面のアルファベット表記。', max_length=20, verbose_name='背ネーム'),
        ),
        migrations.AddField(
            model_name='player',
            name='name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='よみがな'),
        ),
    ]
