# Generated by Django 5.2.10 on 2026-08-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_player_back_name_player_name_kana'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepitchingline',
            name='hit_by_pitch_allowed',
            field=models.IntegerField(default=0, verbose_name='与死球'),
        ),
        migrations.AddField(
            model_name='gamepitchingline',
            name='home_runs_allowed',
            field=models.IntegerField(default=0, verbose_name='被本塁打'),
        ),
    ]
