# Generated by Django 5.2.10 on 2026-08-10 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_gamepitchingline_hit_by_pitch_allowed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='このチームの選手・試合を編集できるユーザー。管理ユーザーは常に編集できます。', related_name='managed_teams', to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
    ]
