# Generated by Django 5.2.10 on 2026-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_team_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebattingline',
            name='batting_order',
            field=models.IntegerField(blank=True, help_text='1〜9。空欄なら並びは末尾になります。', null=True, verbose_name='打順'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='fielding_position',
            field=models.CharField(blank=True, choices=[('投', '投'), ('捕', '捕'), ('一', '一'), ('二', '二'), ('三', '三'), ('遊', '遊'), ('左', '左'), ('中', '中'), ('右', '右'), ('指', '指'), ('打', '打'), ('走', '走')], help_text='この試合で就いた守備。代打は「打」、代走は「走」。', max_length=2, verbose_name='守備位置'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='slot_sequence',
            field=models.IntegerField(default=0, help_text='0 がスタメン。1以上は同じ打順への途中出場です。', verbose_name='交代の順'),
        ),
        migrations.AddField(
            model_name='gamepitchingline',
            name='appearance_order',
            field=models.IntegerField(default=1, verbose_name='登板順'),
        ),
        migrations.AddField(
            model_name='gamepitchingline',
            name='holds',
            field=models.IntegerField(default=0, verbose_name='ホールド'),
        ),
    ]
