# Generated by Django 5.2.10 on 2026-08-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_gamebattingline_batting_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepitchingline',
            name='entered_inning',
            field=models.PositiveIntegerField(default=1, verbose_name='登板した回'),
        ),
        migrations.CreateModel(
            name='GameInningScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.PositiveIntegerField(verbose_name='回')),
                ('is_home', models.BooleanField(help_text='ビジターが表、ホームが裏に攻めます。', verbose_name='ホームの攻撃')),
                ('runs', models.PositiveIntegerField(default=0, verbose_name='得点')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inning_scores', to='myapp.game', verbose_name='試合')),
            ],
            options={
                'verbose_name': 'イニングスコア',
                'verbose_name_plural': 'イニングスコア',
                'ordering': ['inning', 'is_home'],
                'constraints': [models.UniqueConstraint(fields=('game', 'inning', 'is_home'), name='unique_game_inning_half')],
            },
        ),
    ]
