# Generated by Django 5.2.10 on 2026-08-12 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_gamepitchingline_entered_inning_gameinningscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlateAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='試合内の通し番号。1から欠けずに続きます。試合の時系列はこれだけで決まります。', verbose_name='打席の順番')),
                ('inning', models.PositiveIntegerField(verbose_name='回')),
                ('is_bottom', models.BooleanField(help_text='ビジターが表、ホームが裏に攻めます。', verbose_name='ホームの攻撃')),
                ('batting_order', models.PositiveIntegerField(help_text='1〜9。', verbose_name='打順')),
                ('slot_sequence', models.IntegerField(default=0, help_text='0 がスタメン。1以上は同じ打順への途中出場です。', verbose_name='交代の順')),
                ('result', models.CharField(choices=[('単打', '単打'), ('二塁打', '二塁打'), ('三塁打', '三塁打'), ('本塁打', '本塁打'), ('四球', '四球'), ('故意四球', '故意四球'), ('死球', '死球'), ('空振り三振', '空振り三振'), ('見逃し三振', '見逃し三振'), ('ゴロアウト', 'ゴロアウト'), ('フライアウト', 'フライアウト'), ('ライナーアウト', 'ライナーアウト'), ('邪飛', '邪飛'), ('犠打', '犠打'), ('犠飛', '犠飛'), ('失策出塁', '失策出塁'), ('野選出塁', '野選出塁'), ('打撃妨害', '打撃妨害'), ('走塁妨害', '走塁妨害')], max_length=10, verbose_name='結果')),
                ('fielded_by', models.CharField(blank=True, help_text='守備位置を「-」で連ねます（遊ゴロ併殺なら 遊-二-一）。刺殺・補殺の出典です。', max_length=30, verbose_name='打球の処理')),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_appearances', to='myapp.player', verbose_name='打者')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_appearances', to='myapp.game', verbose_name='試合')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_appearances_pitched', to='myapp.player', verbose_name='投手')),
            ],
            options={
                'verbose_name': '打席',
                'verbose_name_plural': '打席',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GameFieldingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('投', '投'), ('捕', '捕'), ('一', '一'), ('二', '二'), ('三', '三'), ('遊', '遊'), ('左', '左'), ('中', '中'), ('右', '右'), ('指', '指'), ('打', '打'), ('走', '走')], max_length=2, verbose_name='守備位置')),
                ('kind', models.CharField(choices=[('捕球', '捕球'), ('送球', '送球'), ('落球', '落球')], max_length=4, verbose_name='失策の種類')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fielding_errors', to='myapp.player', verbose_name='守備者')),
                ('plate_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='myapp.gameplateappearance', verbose_name='打席')),
            ],
            options={
                'verbose_name': '失策',
                'verbose_name_plural': '失策',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GameRunnerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_base', models.IntegerField(choices=[(0, '打者席'), (1, '一塁'), (2, '二塁'), (3, '三塁'), (4, '本塁'), (-1, 'アウト')], verbose_name='進塁前')),
                ('to_base', models.IntegerField(choices=[(0, '打者席'), (1, '一塁'), (2, '二塁'), (3, '三塁'), (4, '本塁'), (-1, 'アウト')], verbose_name='進塁後')),
                ('reason', models.CharField(choices=[('打撃', '打撃'), ('四死球・妨害', '四死球・妨害'), ('押し出し', '押し出し'), ('タッチアップ', 'タッチアップ'), ('盗塁', '盗塁'), ('盗塁刺', '盗塁刺'), ('牽制死', '牽制死'), ('失策', '失策'), ('暴投', '暴投'), ('捕逸', '捕逸'), ('ボーク', 'ボーク'), ('野選', '野選'), ('アウト', 'アウト'), ('封殺', '封殺'), ('走塁死', '走塁死')], max_length=10, verbose_name='理由')),
                ('error_index', models.IntegerField(blank=True, help_text='失策に起因する進塁なら、同じ打席の何番目の失策か（0 から数えます）。', null=True, verbose_name='失策の位置')),
                ('plate_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='myapp.gameplateappearance', verbose_name='打席')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_advances', to='myapp.player', verbose_name='走者')),
            ],
            options={
                'verbose_name': '進塁',
                'verbose_name_plural': '進塁',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GameRunnerSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(choices=[(0, '打者席'), (1, '一塁'), (2, '二塁'), (3, '三塁'), (4, '本塁'), (-1, 'アウト')], verbose_name='塁')),
                ('entering_runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinch_running', to='myapp.player', verbose_name='代走')),
                ('leaving_runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_on_base', to='myapp.player', verbose_name='退く走者')),
                ('plate_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='myapp.gameplateappearance', verbose_name='打席')),
            ],
            options={
                'verbose_name': '代走',
                'verbose_name_plural': '代走',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='gameplateappearance',
            constraint=models.UniqueConstraint(fields=('game', 'sequence'), name='unique_game_plate_appearance'),
        ),
    ]
