# Generated by Django 5.2.10 on 2026-08-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_gameplateappearance_gamefieldingerror_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebattingline',
            name='caught_stealing',
            field=models.IntegerField(default=0, verbose_name='盗塁刺'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='double_plays',
            field=models.IntegerField(default=0, verbose_name='併殺打'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='intentional_walks',
            field=models.IntegerField(default=0, verbose_name='故意四球'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='runs',
            field=models.IntegerField(default=0, verbose_name='得点'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='sacrifice_bunts',
            field=models.IntegerField(default=0, verbose_name='犠打'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='stolen_bases',
            field=models.IntegerField(default=0, verbose_name='盗塁'),
        ),
        migrations.AddField(
            model_name='gamebattingline',
            name='strikeouts',
            field=models.IntegerField(default=0, verbose_name='三振'),
        ),
        migrations.AddField(
            model_name='gamepitchingline',
            name='runs_allowed',
            field=models.IntegerField(default=0, verbose_name='失点'),
        ),
    ]
