# Generated by Django 5.2.10 on 2026-10-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_gamebattingline_team_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamefieldingerror',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fielding_errors', to='myapp.player', verbose_name='守備者'),
        ),
        migrations.AlterField(
            model_name='gameplateappearance',
            name='batter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plate_appearances', to='myapp.player', verbose_name='打者'),
        ),
        migrations.AlterField(
            model_name='gameplateappearance',
            name='pitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plate_appearances_pitched', to='myapp.player', verbose_name='投手'),
        ),
        migrations.AlterField(
            model_name='gamerunneradvance',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runner_advances', to='myapp.player', verbose_name='走者'),
        ),
        migrations.AlterField(
            model_name='gamerunnersubstitution',
            name='entering_runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pinch_running', to='myapp.player', verbose_name='代走'),
        ),
        migrations.AlterField(
            model_name='gamerunnersubstitution',
            name='leaving_runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replaced_on_base', to='myapp.player', verbose_name='退く走者'),
        ),
    ]
