# Generated by Django 5.2.10 on 2026-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_protect_players_in_plate_appearances'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='registered_player_limit',
            field=models.PositiveIntegerField(blank=True, default=70, help_text='登録できる支配下選手の上限人数（育成は数えません）。空欄なら無制限。', null=True, verbose_name='支配下選手登録枠'),
        ),
        migrations.AddField(
            model_name='playerstint',
            name='number_before_promotion',
            field=models.IntegerField(blank=True, help_text='育成から支配下に上がる前の背番号（100以上）。支配下登録年を入れたときは必須です。', null=True, verbose_name='昇格前の背番号'),
        ),
        migrations.AddField(
            model_name='playerstint',
            name='promoted_year',
            field=models.IntegerField(blank=True, help_text='育成から支配下に上がった年。育成で加入し、まだ上がっていなければ空欄。', null=True, verbose_name='支配下登録年'),
        ),
        migrations.AddField(
            model_name='playerstint',
            name='signed_as',
            field=models.CharField(choices=[('支配下', '支配下'), ('育成', '育成')], default='支配下', help_text='支配下または育成。育成の背番号は100以上、支配下は99以下です。', max_length=10, verbose_name='加入時の契約区分'),
        ),
    ]
