# Generated by Django 5.2.10 on 2026-10-02 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_protect_players_in_plate_appearances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=50, verbose_name='リーグ名'),
        ),
        migrations.CreateModel(
            name='PennantWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='世界の名前')),
                ('seed', models.PositiveBigIntegerField(verbose_name='乱数のシード')),
                ('start_year', models.IntegerField(verbose_name='開幕年')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('managed_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_in_worlds', to='myapp.team', verbose_name='受け持つ球団')),
                ('owner', models.ForeignKey(blank=True, help_text='この世界を遊ぶユーザー。ペナントの書き込みはこの人だけに許します。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pennant_worlds', to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
            options={
                'verbose_name': 'ペナントの世界',
                'verbose_name_plural': 'ペナントの世界',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='league',
            name='world',
            field=models.ForeignKey(blank=True, help_text='空なら実データのリーグです。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='myapp.pennantworld', verbose_name='世界'),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(condition=models.Q(('world__isnull', True)), fields=('name',), name='unique_real_league_name'),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.UniqueConstraint(fields=('world', 'name'), name='unique_world_league_name'),
        ),
    ]
