# Generated by Django 5.2.10 on 2026-10-02 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_pennant_world_and_league_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='PennantPlayerRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('growth', models.CharField(choices=[('早熟', '早熟'), ('普通', '普通'), ('晩成', '晩成')], max_length=4, verbose_name='成長型')),
                ('contact', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ミート')),
                ('power', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='パワー')),
                ('eye', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='選球眼')),
                ('speed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='走力')),
                ('fielding', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='守備力')),
                ('stuff', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='球威')),
                ('control', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='制球')),
                ('home_run_avoidance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='一発回避')),
                ('stamina', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='スタミナ')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pennant_ratings', to='myapp.player', verbose_name='選手')),
            ],
            options={
                'verbose_name': 'ペナントの能力',
                'verbose_name_plural': 'ペナントの能力',
                'ordering': ['year', 'player_id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'year'), name='unique_pennant_ratings_player_year'), models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', False), ('control__isnull', True), ('eye__isnull', False), ('fielding__isnull', False), ('home_run_avoidance__isnull', True), ('power__isnull', False), ('speed__isnull', False), ('stamina__isnull', True), ('stuff__isnull', True)), models.Q(('contact__isnull', True), ('control__isnull', False), ('eye__isnull', True), ('fielding__isnull', True), ('home_run_avoidance__isnull', False), ('power__isnull', True), ('speed__isnull', True), ('stamina__isnull', False), ('stuff__isnull', False)), _connector='OR'), name='pennant_ratings_batter_or_pitcher')],
            },
        ),
    ]
