# Generated by Django 5.2.10 on 2026-10-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_pennant_player_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PennantFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='試合日')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='myapp.team', verbose_name='ホーム')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_fixtures', to='myapp.team', verbose_name='ビジター')),
            ],
            options={
                'verbose_name': 'ペナントの日程',
                'verbose_name_plural': 'ペナントの日程',
                'ordering': ['date', 'home_team_id'],
                'constraints': [models.UniqueConstraint(fields=('date', 'home_team', 'visitor_team'), name='unique_pennant_fixture'), models.CheckConstraint(condition=models.Q(('home_team', models.F('visitor_team')), _negated=True), name='pennant_fixture_teams_differ')],
            },
        ),
    ]
