# Generated by Django 5.2.10 on 2026-10-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_backfill_stint_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstint',
            name='acquired_via',
            field=models.CharField(blank=True, choices=[('ドラフト', 'ドラフト'), ('育成ドラフト', '育成ドラフト'), ('FA', 'FA'), ('トレード', 'トレード'), ('自由契約からの獲得', '自由契約からの獲得'), ('新外国人', '新外国人'), ('その他', 'その他')], help_text='この在籍にどう加わったか。空欄は不明です（推測では埋めません）。育成ドラフトは育成、ドラフトは支配下で加入した在籍だけ選べます。FA は、加入年の前年の FA 宣言が必要です（オフの FA 移籍は宣言の翌年に加入として記録します）。', max_length=20, null=True, verbose_name='入団の経路'),
        ),
        migrations.CreateModel(
            name='PlayerFreeAgentDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='宣言した年に、どこかの球団に在籍している必要があります。', verbose_name='宣言した年')),
                ('kind', models.CharField(choices=[('国内', '国内'), ('海外', '海外')], default='国内', help_text='国内 FA か海外 FA か。残留したか移籍したかは在籍から導くので入力しません。', max_length=10, verbose_name='種別')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_declarations', to='myapp.player', verbose_name='選手')),
            ],
            options={
                'verbose_name': 'FA 宣言',
                'verbose_name_plural': 'FA 宣言',
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('player', 'year'), name='unique_fa_declaration_player_year')],
            },
        ),
    ]
