# Generated by Django 5.2.10 on 2026-10-06 14:29
# 背番号を整数から表記の文字列にする（00 を 0 と区別するため。#157）。整数→文字列の値の変換は DB が行う。
# 逆に戻すと「00」は整数の 0 に潰れ、同じチームの「0」と重複しうる（手で戻すときは注意）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_acquisition_route_and_fa_declaration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerstint',
            options={'ordering': ['-from_year', 'id'], 'verbose_name': '在籍', 'verbose_name_plural': '在籍'},
        ),
        migrations.AlterField(
            model_name='playerstint',
            name='number',
            field=models.CharField(help_text='0・00・1〜999。「0」と「00」は別の番号です。', max_length=3, verbose_name='背番号'),
        ),
        migrations.AlterField(
            model_name='playerstint',
            name='number_before_promotion',
            field=models.CharField(blank=True, help_text='育成から支配下に上がる前の背番号（3桁・100以上）。支配下登録年を入れたときは必須です。', max_length=3, null=True, verbose_name='昇格前の背番号'),
        ),
        migrations.AlterField(
            model_name='playerstint',
            name='signed_as',
            field=models.CharField(choices=[('支配下', '支配下'), ('育成', '育成')], default='支配下', help_text='支配下または育成。育成の背番号は3桁（100以上）、支配下は00・0〜99です。', max_length=10, verbose_name='加入時の契約区分'),
        ),
    ]
