# Generated by Django 5.2.10 on 2026-10-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_pennant_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PennantClubPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closer', models.ForeignKey(blank=True, help_text='空なら自動（AI 監督が決める）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='myapp.player', verbose_name='抑え')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_plan', to='myapp.team', verbose_name='球団')),
            ],
            options={
                'verbose_name': 'ペナントの編成',
                'verbose_name_plural': 'ペナントの編成',
                'ordering': ['team_id'],
            },
        ),
        migrations.CreateModel(
            name='PennantClubPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('active', '1軍登録'), ('lineup', 'オーダー'), ('rotation', 'ローテーション')], max_length=10, verbose_name='区画')),
                ('order', models.PositiveSmallIntegerField(verbose_name='順')),
                ('fielding_position', models.CharField(blank=True, choices=[('投', '投'), ('捕', '捕'), ('一', '一'), ('二', '二'), ('三', '三'), ('遊', '遊'), ('左', '左'), ('中', '中'), ('右', '右'), ('指', '指'), ('打', '打'), ('走', '走')], default='', max_length=2, verbose_name='守備位置')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='myapp.pennantclubplan', verbose_name='編成')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.player', verbose_name='選手')),
            ],
            options={
                'verbose_name': 'ペナントの編成の行',
                'verbose_name_plural': 'ペナントの編成の行',
                'ordering': ['plan_id', 'section', 'order'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'section', 'player'), name='unique_pennant_plan_entry_player'), models.UniqueConstraint(fields=('plan', 'section', 'order'), name='unique_pennant_plan_entry_order'), models.CheckConstraint(condition=models.Q(models.Q(('fielding_position__gt', ''), ('section', 'lineup')), models.Q(models.Q(('section', 'lineup'), _negated=True), ('fielding_position', '')), _connector='OR'), name='pennant_plan_entry_position_only_in_lineup')],
            },
        ),
    ]
